### ISSUE TITLE
Unable to reproduce performance

### ISSUE THREAD

**Issue by Nonmy** [nomewang/M3DM#10]
Could you please provide a training and testing script exactly follow the paper. I followed the script and checkpoint provided in the repo and get result as below:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:s<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-m	IAUCROC	PAUCROC AUPRO
bagel	0.864	0.979	0.92
gland	0.551	0.969	0.902
carrot	0.777	0.995	0.975
cookie	0.866	0.948	0.867
dowel	0.717	0.98	0.918
foam	0.656	0.951	0.841
peach	0.64	0.985	0.945
potato	0.668	0.988	0.947
rope	0.924	0.987	0.955
tire	0.48	0.937	0.787
mean	0.714	0.972	0.906
icrosoft-com:office:office"
 #xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/12786/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/12786/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

  | IAUCROC | PAUCROC | AUPRO
-- | -- | -- | --
bagel | 0.864 | 0.979 | 0.92
cable gland | 0.551 | 0.969 | 0.902
carrot | 0.777 | 0.995 | 0.975
cookie | 0.866 | 0.948 | 0.867
dowel | 0.717 | 0.98 | 0.918
foam | 0.656 | 0.951 | 0.841
peach | 0.64 | 0.985 | 0.945
potato | 0.668 | 0.988 | 0.947
rope | 0.924 | 0.987 | 0.955
tire | 0.48 | 0.937 | 0.787
mean | 0.714 | 0.972 | 0.906

</body>

**Comment by nomewang** [comment]
We will provide more detailed scripts soon, before that, you can try this pretrained checkpoint file of [UFF module](https://drive.google.com/file/d/1Z2AkfPqenJEv-IdWhVdRcvVQAsJC4DxW/view?usp=sharing).

**Comment by Nonmy** [comment]
Thanks for the timely reply and the pretrained checkpoint.
