### ISSUE TITLE
Different preprocessing in the paper and the code

### ISSUE THREAD

**Issue by LeeeeTX** [nomewang/M3DM#14]
When preprocessing, according to your paper, you set the background of point cloud and rgb image to 0. But when I go through the code, I found that in processing.py, you didn't saved the processed rgb image (you commented out these lines). May I ask whether this is intentional or not, or should I run the 124-line "Image.fromarray(organized_clustered_rgb).save(rgb_path)" when I reproduce the experiment?
Thanks a lot!

**Comment by LiZhi-CASIA** [comment]
Hello, I have the same problem as you, did you solve it?

**Comment by nomewang** [comment]
Thanks for the feedback. This was a bug in the release version and we have removed this comment in the updated code.
