### ISSUE TITLE
test wrong

### ISSUE THREAD

**Issue by YongZh958** [nomewang/M3DM#3]
(m3dm) root@d12f2348ebf0:~/ZY/model/M3DM# python3 main.py --method_name DINO+Point_MAE --memory_bank multiple --rgb_backbone_name vit_base_patch8_224_dino --xyz_backbone_name Point_MAE --save_feature 
Extracting train features for class bagel: 100%|???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 244/244 [08:19<00:00,  2.05s/it]

Running coreset for DINO+Point_MAE on class bagel...
   Fitting random projections. Start dim = torch.Size([765184, 1152]).
Killed

**Comment by nomewang** [comment]
Maybe the memory is inefficient, and try to use fewer samples to build memory banks with `--max_sample` .

**Comment by YongZh958** [comment]
Thanks for your help. I solve this problem successfully！

**Comment by leo19910821** [comment]
I am having the same issue. How did you solve it??
