### ISSUE TITLE
When I build the environment, I encounter a error. Can you fix it?

### ISSUE THREAD

**Issue by limaodaxia** [nomewang/M3DM#5]
× git clone --filter=blob:none --quiet git://github.com/erikwijmans/Pointnet2_PyTorch.git 'C:\Users\limaodaxia\AppData\Local\Temp\pip-install-uz5c90xe\pointnet2-ops_0
cea27ebf028479bb8eec4ff27e3a84f' did not run successfully.
│ exit code: 128
╰─> See above for output.

**Comment by nomewang** [comment]
We didn't test the code on Windows platform, and we recommend you to use Linux system to try this project.
`pointnet2-ops` maybe not able to run on the Windows.

**Comment by limaodaxia** [comment]
thank you，I solved the problem by changing the command. What I used is pip install "git+http://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib"
