### ISSUE TITLE
Do I need to decompress the dataset after I download it？

### ISSUE THREAD

**Issue by limaodaxia** [nomewang/M3DM#8]
I downloaded the file "mvtec_3d_anomaly_detection.tar.xz". Do I need to decompress it? Besides,  according to the command "python utils/preprocessing.py datasets/mvtec3d/", Should I put the file "mvtec_3d_anomaly_detection.tar.xz" in "datasets/mvtec3d/"?

**Comment by nomewang** [comment]
Yes, just decompress the `.tar.xz` file and put it in a folder.
