### ISSUE TITLE
RUNNING environment

### ISSUE THREAD

**Issue by AlanSky815** [nomewang/M3DM#9]
When I install poinnet2_ops(pip install "git+git://github.com/erikwijmans/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib"), encountering: 

can you give me some suggestions(and cuda=11.3 linux16.04, pytorch1.9)?
<img width="746" alt="1" src="https://github.com/nomewang/M3DM/assets/31244745/f6584fdc-f623-4cac-b1b3-763cb02a3b88">
<img width="889" alt="2" src="https://github.com/nomewang/M3DM/assets/31244745/51fe90a0-a6eb-4921-a8ec-721cf6712042">

**Comment by nomewang** [comment]
I didn't meet this problem before.
It seems that `_version.py` is missing, you try to download the repo, and directly build the package with `pip install pointnet2_ops_lib/.`

**Comment by AlanSky815** [comment]
Thanks, I have already solved it.

**Comment by cnmcnm111** [comment]
> 谢谢，我已经解决了。

Mr. Liu of Zunjin, hello, I have a similar problem with you, which is very difficult, may I ask how you solve it? Our research fields should be similar. In order to facilitate discussion and communication in the future, is it convenient to add the contact information?

**Comment by cnmcnm111** [comment]
> Thanks, I have already solved it.

Hello, Mr. Liu , I have a similar problem with you, which is very difficult, may I ask how you solve it? Our research fields should be similar. In order to facilitate discussion and communication in the future, is it convenient to add the contact information?

**Comment by limaodaxia** [comment]
Hello，Mr-AlanLiu, how you fixed it？

**Comment by limaodaxia** [comment]
> Thanks, I have already solved it.

Hello, how you fixed it?

**Comment by AlanSky815** [comment]
> 

this issue is caused by your running environment, please refer to the link: https://github.com/erikwijmans/Pointnet2_PyTorch/issues/139
https://github.com/erikwijmans/Pointnet2_PyTorch/issues/129
